git :
  commit : '@git.commit.id.abbrev@'
  build_time : '@git.build.time@'

info :
  app :
    name : '@project.name@'
    description : '@project.description@'
    version : '@project.version@'
    git_commit : ${git.commit}
    build_time : ${git.build_time}

spring :
  application :
    name : words-processing
  jackson :
    default-property-inclusion : NON_NULL
  lifecycle :
    timeout-per-shutdown-phase : ${TIMEOUT_PER_SHUTDOWN:20s}
  groovy :
    template :
      check-template-location : false
  kafka :
    producer :
      bootstrap-servers : ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      value-serializer : org.springframework.kafka.support.serializer.JsonSerializer
      properties :
        security.protocol : ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
        sasl.mechanism : SCRAM-SHA-512
    admin :
      properties :
        bootstrap.servers : ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
        security.protocol : ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
        sasl.mechanism : SCRAM-SHA-512
  devtools :
    add-properties : false
    restart :
      enabled : false
    livereload :
      enabled : false

server :
  port : ${SERVER_PORT:8085}
  shutdown : graceful
  forward-headers-strategy : framework
  tomcat:
    redirect-context-root : false


management :
  health :
    livenessstate :
      enabled : true
    readinessstate :
      enabled : true
    kafka :
      enabled : true
      response-timeout : 500

  info :
    env :
      enabled : true
    java :
      enabled : true
    os :
      enabled : true

  server :
    port : ${MANAGEMENT_SERVER_PORT:8080}
    add-application-context-header : true

  metrics :
    tags :
      application : ${spring.application.name}
      profiles : ${spring.profiles.active}
    distribution :
      percentiles-histogram :
        http :
          server :
            requests : true
  tracing :
    sampling :
      probability : 1.0
    enabled : true
  prometheus :
    metrics :
      export :
        step : 20s
        enabled: true
  zipkin :
    tracing :
      endpoint : ${TEMPO_URL:http://localhost:9411/api/v2/spans}

  endpoints :
    enabled-by-default : false
    web :
      exposure :
        include : health, metrics, prometheus, info, env, kafka, openapi, swagger-ui
  endpoint :
    health :
      enabled : true
      show-details : always
      probes :
        enabled : true
    info :
      enabled : true
      show-values : always
    env :
      enabled : true
      show-values : always
    prometheus :
      enabled : true

embedded :
  kafka :
    enabled : false
    docker-image-version : 7.2.1


lorem :
  build :
    description : '@project.description@'
    relative-path : ${SWAGGER_UI_RELATIVE_PATH:}
    version : '@project.version@'
  net-client :
    api-server-url-template : https://loripsum.net/api/{paragraphsNum}/{lengthType}
    connect-timeout : 1  # in sec.
    request-timeout : 2
  kafka :
    admin :
      create-topics : ${KAFKA_ADMIN_CREATES_TOPICS:true}
    topics :
      words-processed :
        name : ${KAFKA_TOPIC_WORDS_PROCESSED:words.processed}
        partitions : ${KAFKA_TOPIC_PARTITIONS_WORDS_PROCESSED:4}
        retention : ${KAFKA_TOPIC_RETENTION_WORDS_PROCESSED:30m}
    error-handling :
      dead-letter :
        retention : 1d
        suffix : .DLT
      backoff :
        initial-interval : 500ms
        max-interval : 2s
        max-retries : 4
        multiplier : 1.5

springdoc :
  show-actuator : false
  swagger-ui :
    config-url : ${SWAGGER_UI_RELATIVE_PATH:/}v3/api-docs/swagger-config
    url : ${SWAGGER_UI_RELATIVE_PATH:/}v3/api-docs
