git :
  commit : '@git.commit.id.abbrev@'
  build_time : '@git.build.time@'

info :
  app :
    name : '@project.name@'
    description : '@project.description@'
    version : '@project.version@'
    git_commit : ${git.commit}
    build_time : ${git.build_time}

spring :
  application :
    name : reports-history
  liquibase :
    change-log : migrations/master.xml
  datasource :
    type : com.zaxxer.hikari.HikariDataSource
    url : ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/lorem_db}
    username : ${DATASOURCE_USERNAME:postgres}
    password : ${DATASOURCE_PASSWORD:postgres}
    driver-class-name : ${DATASOURCE_DRIVER:org.postgresql.Driver}
    hikari :
      pool-name : Hikari
      auto-commit : false
  jpa :
    hibernate :
      ddl-auto : none
      naming :
        physical-strategy : org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy : org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    open-in-view : true
    properties :
      hibernate.jdbc.time_zone : UTC
      hibernate.id.new_generator_mappings : true
      hibernate.connection.provider_disables_autocommit : true
      hibernate.cache.use_second_level_cache : true
      hibernate.cache.use_query_cache : true
      hibernate.generate_statistics : false
      # modify batch size as necessary
      hibernate.jdbc.batch_size : 25
      hibernate.order_inserts : true
      hibernate.order_updates : true
      hibernate.query.fail_on_pagination_over_collection_fetch : true
      hibernate.query.in_clause_parameter_padding : true
    show-sql : false
  devtools :
    add-properties : false
    restart :
      enabled : false
    livereload :
      enabled : false

  jackson :
    default-property-inclusion : NON_NULL
  lifecycle :
    timeout-per-shutdown-phase : ${TIMEOUT_PER_SHUTDOWN:20s}
  groovy :
    template :
      check-template-location : false

  kafka :
    consumer :
      bootstrap-servers : ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      value-deserializer : org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset : earliest
      properties :
        security.protocol : ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
        sasl.mechanism : SCRAM-SHA-512
        isolation.level : read_committed
        spring.json.trusted.packages : '*'
      group-id : ${KAFKA_CONSUMERS_GROUP:reports-history}
    producer :
      bootstrap-servers : ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      value-serializer : org.springframework.kafka.support.serializer.JsonSerializer
      properties :
        security.protocol : ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
        sasl.mechanism : SCRAM-SHA-512
    admin :
      properties :
        bootstrap.servers : ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
        security.protocol : ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
        sasl.mechanism : SCRAM-SHA-512

server :
  port : ${SERVER_PORT:8086}
  shutdown : graceful
  forward-headers-strategy : framework
  tomcat:
    redirect-context-root : false

logging :
  pattern :
    level : '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level :
    ROOT : ${LOGGING_LEVEL_ROOT:INFO}
    liquibase : INFO
management :
  health :
    livenessstate :
      enabled : true
    readinessstate :
      enabled : true
    kafka :
      enabled : true
      response-timeout : 500
  info :
    env :
      enabled : true
    java :
      enabled : true
    os :
      enabled : true
  server :
    port : ${MANAGEMENT_SERVER_PORT:8080}
    add-application-context-header : true

  metrics :
    tags :
      application : ${spring.application.name}
      profiles : ${spring.profiles.active}
    distribution :
      percentiles-histogram :
        http :
          server :
            requests : true
  tracing :
    sampling :
      probability : 1.0
    enabled : true
  prometheus :
    metrics :
      export :
        step : 20s
        enabled: true
  zipkin :
    tracing :
      endpoint : ${TEMPO_URL:http://localhost:9411/api/v2/spans}

  endpoints :
    enabled-by-default : false
    web :
      exposure :
        include : health, metrics, prometheus, info, env, kafka, openapi, swagger-ui
  endpoint :
    health :
      enabled : true
      show-details : always
      probes :
        enabled : true
    info :
      enabled : true
    env :
      enabled : true
    prometheus :
      enabled : true

embedded :
  postgresql :
    enabled : false
    docker-image-version : 13.11
  kafka :
    enabled : false
    docker-image-version : 7.2.1


lorem :
  build :
    description : '@project.description@'
    relative-path : ${SERVER_SERVLET_CONTEXT_PATH:/}
    version : '@project.version@'
  kafka :
    admin :
      create-topics : ${KAFKA_ADMIN_CREATES_TOPICS:true}
    error-handling :
      dead-letter :
        retention : 1d
        suffix : .DLT
      backoff :
        initial-interval : 500ms
        max-interval : 2s
        max-retries : 4
        multiplier : 1.5
    consumer :
      threads : ${KAFKA_CONSUMER_THREADS:4}
    topics :
      words-processed :
        name : ${KAFKA_TOPIC_WORDS_PROCESSED:words.processed}
        partitions : ${KAFKA_TOPIC_PARTITIONS_WORDS_PROCESSED:4}
        retention : ${KAFKA_TOPIC_RETENTION_WORDS_PROCESSED:30m}

springdoc :
  show-actuator : false
